# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Digital BT(933642d7-459a-499f-acc7-0d9a14ecf604)'
    subscriptionId: '933642d7-459a-499f-acc7-0d9a14ecf604'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CareerCircleWeb'
    location: 'South Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sirforce/apiechodev/master/templates/staging-careercircle-api2-staging-api.template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/sirforce/apiechodev/master/templates/staging-careercircle-parameters.json'
    deploymentMode: 'Validation'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'templates'
    ArtifactName: 'drop-dev'
    publishLocation: 'Container'